Default shiftKey behavior on transformer
konvajs/konva pull request #1452
Opened 2022-11-17 10:12 UTC by pro-nav

2022-11-17 10:14 UTC, pro-nav commented
https://github.com/konvajs/konva/issues/1453#issue-1453071723

2022-11-27 14:33 UTC, Pi-Bouf requested changes

2022-11-27 14:33 UTC, Pi-Bouf commented on src/shapes/Transformer.ts
> +Factory.addGetterSetter(Transformer, 'shiftBehavior', "default");
Keep single quote on the `default` value !

2022-12-07 09:57 UTC, Pi-Bouf approved these changes

2022-12-15 06:43 UTC, MrHeer approved these changes
LGTM

2022-12-17 15:00 UTC, lavrton commented
Please fix tests. I am ok to merge it.

2023-04-16 04:11 UTC, lavrton commented
Merged in https://github.com/konvajs/konva/pull/1535

2023-04-16 04:11 UTC, closed without merging